import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_build",
  description:
    "Generate implementation prompts and a build checklist — writes build.md. Does not edit source files directly; use the included prompts in your AI coding tool. Run after waypoint_plan.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root. Defaults to the current working directory.",
      },
      task: {
        type: "string",
        description:
          "Specific build task or milestone to implement (optional). Omit to build from the full plan.",
      },
    },
    required: [],
  },
};

export async function run(args: {
  workspacePath?: string;
  task?: string;
}): Promise<string> {
  const { workspacePath = process.cwd(), task } = args;

  const ctx = await getBaseContext(workspacePath);
  const planArtifact = await getArtifact(workspacePath, "plan.md");
  const goalArtifact = await getArtifact(workspacePath, "goal.md");

  if (!planArtifact && !goalArtifact) {
    return [
      "## waypoint_build — No plan or goal found",
      "",
      "Run `waypoint_goal` → `waypoint_plan` before building.",
    ].join("\n");
  }

  const goalLine = goalArtifact?.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";
  const hasPlan = !!planArtifact;

  const pkgName = (() => {
    try {
      return JSON.parse(ctx.packageJson ?? "{}").name ?? "this project";
    } catch {
      return "this project";
    }
  })();

  const artifact = [
    "# Build",
    "",
    `**Goal:** ${goalLine}`,
    task ? `**Task:** ${task}` : "",
    !hasPlan ? "\n> ⚠️ No plan.md found — consider running `waypoint_plan` first." : "",
    "",
    "## Implementation checklist",
    "<!-- Track each implementation unit -->",
    "- [ ] Set up project structure / scaffold",
    "- [ ] Implement core logic",
    "- [ ] Wire up integrations",
    "- [ ] Handle edge cases and errors",
    "- [ ] Self-review before handoff to waypoint_test",
    "",
    "## AI coding prompts",
    "<!-- Paste these into your AI coding tool (Claude Code, Cursor, etc.) -->",
    "",
    "### Scaffold prompt",
    "```",
    `Scaffold the implementation for: ${task ?? goalLine}`,
    `Project: ${pkgName}`,
    "Requirements:",
    "- [fill from plan milestones]",
    "- Keep changes minimal and focused",
    "- No speculative features",
    "```",
    "",
    "### Implementation prompt",
    "```",
    `Implement: ${task ?? goalLine}`,
    "Constraints:",
    "- Match existing code style",
    "- No new dependencies unless necessary",
    "- Write no comments unless the why is non-obvious",
    "```",
    "",
    "## Implementation notes",
    "<!-- Record decisions made during build, gotchas, deviations from plan -->",
    "- ",
    "",
    "## Files changed",
    "<!-- List key files created or modified -->",
    "- ",
    "",
    `_Generated by waypoint_build — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "build.md", artifact);

  return [
    "## waypoint_build — Build guide generated",
    "",
    `**Goal:** ${goalLine}`,
    task ? `**Task:** ${task}` : "",
    !hasPlan ? "\n> No plan.md found — output may be generic. Run `waypoint_plan` first." : "",
    "",
    "### AI coding prompts included",
    "- **Scaffold prompt** — use to create initial structure",
    "- **Implementation prompt** — use for each milestone or task",
    "",
    "### Artifact saved",
    "`build.md` written to `.waypoint/build.md`.",
    "Fill in the implementation checklist as you work.",
    "",
    "### Suggested next step",
    "Run `waypoint_test` to verify feature-level requirements once implementation is ready.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
