import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_compare",
  description:
    "Present decision tradeoffs, comparison methods, UI mockups if relevant.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
      decision: {
        type: "string",
        description:
          "Specific decision to evaluate (optional). Omit to evaluate all open decisions from research.",
      },
    },
    required: ["workspacePath"],
  },
};

export async function run(args: {
  workspacePath: string;
  decision?: string;
}): Promise<string> {
  const { workspacePath, decision } = args;

  const ctx = await getBaseContext(workspacePath);
  const goalArtifact = await getArtifact(workspacePath, "goal.md");
  const researchArtifact = await getArtifact(workspacePath, "research.md");

  if (!goalArtifact) {
    return [
      "## waypoint_compare — No goal found",
      "",
      "Run `waypoint_goal` first, then `waypoint_research` before evaluating options.",
    ].join("\n");
  }

  const goalLine = goalArtifact.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";
  const hasResearch = !!researchArtifact;

  const artifact = [
    "# Options",
    "",
    `**Goal:** ${goalLine}`,
    decision ? `**Decision under evaluation:** ${decision}` : "",
    !hasResearch ? "\n> ⚠️ No research.md found — options may be incomplete. Run `waypoint_research` first." : "",
    "",
    "## Decision log",
    "<!-- Record each key decision, the options considered, and the choice made -->",
    "",
    "### Decision 1",
    `**Question:** ${decision ?? "What approach best satisfies the goal?"}`,
    "",
    "| Option | Pros | Cons | Fit |",
    "|--------|------|------|-----|",
    "| Option A | | | |",
    "| Option B | | | |",
    "| Option C | | | |",
    "",
    "**Recommended:** <!-- State your recommendation and the deciding factor -->",
    "**Rationale:** <!-- Why this option over the others? -->",
    "",
    "## Eliminated approaches",
    "<!-- Options ruled out early and why — prevents revisiting dead ends -->",
    "- ",
    "",
    "## Assumptions & constraints",
    "<!-- What must be true for the chosen option to work? -->",
    "- ",
    "",
    `_Generated by waypoint_compare — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "compare.md", artifact);

  return [
    "## waypoint_compare — Decision framework generated",
    "",
    `**Goal:** ${goalLine}`,
    decision ? `**Decision focus:** ${decision}` : "",
    !hasResearch
      ? "\n> No research.md found — consider running `waypoint_research` first for more informed options."
      : "",
    "",
    "### How to use compare.md",
    "1. Fill in the decision table — one row per option",
    "2. State pros, cons, and fit for each",
    "3. Write a **Recommended** line with clear rationale",
    "4. List eliminated approaches to avoid revisiting them",
    "",
    "### Artifact saved",
    "`compare.md` written to `.waypoint/compare.md`.",
    "",
    "### Suggested next step",
    "Run `waypoint_plan` once decisions are recorded.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
