import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_debug",
  description:
    "Diagnostic frameworks for a reported symptom — writes debug.md. Does not edit source files or run code. Mode troubleshoot = root cause framing (default, works for most problems); mode trace = execution path analysis.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root. Defaults to the current working directory.",
      },
      mode: {
        type: "string",
        enum: ["troubleshoot", "trace"],
        description:
          "troubleshoot = root cause framing (default — use when you're not sure). trace = execution path analysis, use when you need to follow exactly what runs step by step.",
      },
      symptom: {
        type: "string",
        description: "Observed symptom or failure to diagnose (optional).",
      },
    },
    required: [],
  },
};

export async function run(args: {
  workspacePath?: string;
  mode?: "troubleshoot" | "trace";
  symptom?: string;
}): Promise<string> {
  const { workspacePath = process.cwd(), mode = "troubleshoot", symptom } = args;

  const ctx = await getBaseContext(workspacePath);
  const buildArtifact = await getArtifact(workspacePath, "build.md");
  const goalArtifact = await getArtifact(workspacePath, "goal.md");

  const goalLine = goalArtifact?.match(/^# Goal\n+(.+)/m)?.[1] ?? "(no goal defined)";
  const focus = symptom ?? "unspecified symptom";

  let modeContent: string[];

  if (mode === "troubleshoot") {
    modeContent = [
      "## Troubleshoot — Root cause framing",
      "",
      `**Symptom:** ${focus}`,
      "",
      "### Is/Is-not analysis",
      "| Dimension | Is | Is Not |",
      "|-----------|-----|--------|",
      "| What | | |",
      "| Where | | |",
      "| When | | |",
      "| Extent | | |",
      "",
      "### Root cause hypotheses",
      "<!-- Rank by likelihood — most likely first -->",
      "1. ",
      "2. ",
      "3. ",
      "",
      "### Diagnostic steps",
      "<!-- Ordered read-only checks to confirm or rule out each hypothesis -->",
      "- [ ] Check logs for errors around the time of symptom",
      "- [ ] Reproduce symptom in isolation",
      "- [ ] Identify the last known good state",
      "- [ ] Diff current state against known good",
      "",
      "### AI diagnostic prompt",
      "```",
      `Diagnose the following symptom without modifying any code: ${focus}`,
      "",
      "Steps:",
      "1. Identify the likely root cause",
      "2. List evidence that supports or refutes each hypothesis",
      "3. Propose the minimal targeted fix — do not implement it yet",
      "```",
    ];
  } else {
    modeContent = [
      "## Trace — Execution path analysis",
      "",
      `**Symptom:** ${focus}`,
      "",
      "### Entry point",
      "<!-- Where does execution begin for this flow? -->",
      "- ",
      "",
      "### Execution path",
      "<!-- Step-by-step: function → function → output -->",
      "1. ",
      "2. ",
      "3. ",
      "",
      "### Observed vs expected at each step",
      "| Step | Expected | Observed | Diverges? |",
      "|------|----------|----------|-----------|",
      "| | | | |",
      "",
      "### Divergence point",
      "<!-- Where exactly does actual behavior first differ from expected? -->",
      "- ",
      "",
      "### AI trace prompt",
      "```",
      `Trace the execution path for: ${focus}`,
      "",
      "Without modifying any code:",
      "1. Follow the call chain from entry point to output",
      "2. Identify where the observed behavior first diverges from expected",
      "3. Explain why that divergence occurs",
      "```",
    ];
  }

  const artifact = [
    "# Diagnose",
    "",
    `**Mode:** ${mode}`,
    `**Goal context:** ${goalLine}`,
    !buildArtifact ? "\n> ⚠️ No build.md found — diagnosis has no build baseline." : "",
    "",
    ...modeContent,
    "",
    "## Workspace snapshot",
    `**Files:** \n\`\`\`\n${ctx.fileTree}\n\`\`\``,
    "",
    `_Generated by waypoint_debug (${mode}) — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "debug.md", artifact);

  return [
    `## waypoint_debug — ${mode === "troubleshoot" ? "Troubleshoot" : "Trace"} guide generated`,
    "",
    `**Mode:** ${mode}`,
    `**Symptom:** ${focus}`,
    "",
    mode === "troubleshoot"
      ? [
          "### Framework: Is/Is-not analysis",
          "Define what the symptom IS and IS NOT across: what, where, when, extent.",
          "Rank hypotheses by likelihood. Run diagnostic steps read-only first.",
        ].join("\n")
      : [
          "### Framework: Execution path trace",
          "Map the call chain from entry point to output.",
          "Find the exact step where observed behavior diverges from expected.",
        ].join("\n"),
    "",
    "### Artifact saved",
    "`debug.md` written to `.waypoint/debug.md`.",
    "",
    "### Suggested next step",
    "Run `waypoint_fix` once the root cause is confirmed.",
  ].join("\n");
}
