import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_document",
  description:
    "Generate a documentation scaffold for the current project state — writes docs.md. Does not edit source files.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root. Defaults to the current working directory.",
      },
      audience: {
        type: "string",
        description:
          "Intended audience for the documentation (optional). E.g. 'new contributors', 'end users', 'API consumers'.",
      },
    },
    required: [],
  },
};

export async function run(args: {
  workspacePath?: string;
  audience?: string;
}): Promise<string> {
  const { workspacePath = process.cwd(), audience } = args;

  const ctx = await getBaseContext(workspacePath);
  const goalArtifact = await getArtifact(workspacePath, "goal.md");
  const buildArtifact = await getArtifact(workspacePath, "build.md");
  const planArtifact = await getArtifact(workspacePath, "plan.md");

  const goalLine = goalArtifact?.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not defined)";

  const pkgInfo = (() => {
    try {
      const p = JSON.parse(ctx.packageJson ?? "{}");
      return { name: p.name ?? "this project", version: p.version ?? "0.0.0", description: p.description ?? "" };
    } catch {
      return { name: "this project", version: "0.0.0", description: "" };
    }
  })();

  const targetAudience = audience ?? "contributors and users";

  const artifact = [
    "# Documentation",
    "",
    `**Project:** ${pkgInfo.name} v${pkgInfo.version}`,
    pkgInfo.description ? `**Description:** ${pkgInfo.description}` : "",
    `**Audience:** ${targetAudience}`,
    "",
    "## What this is",
    `<!-- 2-3 sentences explaining what ${pkgInfo.name} does and why it exists -->`,
    goalLine !== "(goal not defined)" ? goalLine : "",
    "",
    "## How it works",
    "<!-- High-level architecture or flow — no code, just concepts -->",
    "",
    "```",
    ctx.fileTree,
    "```",
    "",
    "## Getting started",
    "",
    "### Prerequisites",
    "- ",
    "",
    "### Installation",
    "```sh",
    "# installation steps",
    "```",
    "",
    "### Quick start",
    "```sh",
    "# minimal working example",
    "```",
    "",
    "## Key concepts",
    "<!-- Define the 3-5 concepts a reader must understand to use this effectively -->",
    "",
    "### Concept 1",
    "<!-- What it is and why it matters -->",
    "",
    "## Reference",
    "<!-- API, CLI flags, configuration options — one sub-section per entry point -->",
    "",
    "## Known limitations",
    "- ",
    "",
    `_Generated by waypoint_document — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "docs.md", artifact);

  return [
    "## waypoint_document — Documentation generated",
    "",
    `**Project:** ${pkgInfo.name} v${pkgInfo.version}`,
    `**Audience:** ${targetAudience}`,
    "",
    "### Sections scaffolded",
    "- **What this is** — project purpose pulled from goal.md",
    "- **How it works** — architecture overview with file tree",
    "- **Getting started** — prerequisites, install, quick start",
    "- **Key concepts** — fill in 3-5 concepts readers need",
    "- **Reference** — API/CLI/config reference",
    "- **Known limitations** — be honest about what doesn't work yet",
    "",
    "### Artifact saved",
    "`docs.md` written to `.waypoint/docs.md`.",
    "",
  ].join("\n");
}
