import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_fix",
  description: "Targeted bug patches with minimal footprint.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
      bug: {
        type: "string",
        description: "Description of the bug to fix (optional). Omit to review existing fix.md.",
      },
    },
    required: ["workspacePath"],
  },
};

export async function run(args: {
  workspacePath: string;
  bug?: string;
}): Promise<string> {
  const { workspacePath, bug } = args;

  const ctx = await getBaseContext(workspacePath);
  const buildArtifact = await getArtifact(workspacePath, "build.md");
  const goalArtifact = await getArtifact(workspacePath, "goal.md");
  const existingFix = await getArtifact(workspacePath, "fix.md");

  if (!bug && !existingFix) {
    return [
      "## waypoint_fix — No bug description provided",
      "",
      "Call `waypoint_fix` with a `bug` parameter describing the problem.",
      "Example: _\"Tool returns isError:true when workspacePath has spaces\"_",
      "",
      !buildArtifact ? "Run `waypoint_build` first to establish a build baseline." : "",
    ]
      .filter(Boolean)
      .join("\n");
  }

  const bugStatement = bug ?? existingFix?.match(/^## Bug\n+(.+)/m)?.[1] ?? "(bug not parsed)";
  const goalLine = goalArtifact?.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";
  const hasBuild = !!buildArtifact;

  const artifact = [
    "# Fix",
    "",
    `## Bug`,
    bugStatement,
    "",
    `**Goal context:** ${goalLine}`,
    !hasBuild ? "\n> ⚠️ No build.md found — fix has no established baseline." : "",
    "",
    "## Root cause hypothesis",
    "<!-- What is causing this bug? Be specific. -->",
    "- ",
    "",
    "## Fix approach",
    "**Principle:** minimal footprint — change only what is necessary to fix this bug.",
    "",
    "### AI fix prompt",
    "```",
    `Fix the following bug: ${bugStatement}`,
    "",
    "Constraints:",
    "- Change only the code required to fix this specific bug",
    "- Do not refactor surrounding code",
    "- Do not add features or improve unrelated behavior",
    "- Verify the fix does not break adjacent functionality",
    "```",
    "",
    "## Changes made",
    "<!-- List exact files and lines changed -->",
    "| File | Line(s) | Change |",
    "|------|---------|--------|",
    "| | | |",
    "",
    "## Verification",
    "- [ ] Bug no longer reproduced with original steps",
    "- [ ] No regressions in adjacent functionality",
    "- [ ] Fix is the minimum change required",
    "",
    `_Generated by waypoint_fix — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "fix.md", artifact);

  return [
    "## waypoint_fix — Fix guide generated",
    "",
    `**Bug:** ${bugStatement}`,
    !hasBuild ? "\n> No build.md found — fix has no baseline context." : "",
    "",
    "### Approach",
    "- Minimal footprint: only change what fixes this bug",
    "- AI fix prompt included — paste into Claude Code or Cursor",
    "- Verification checklist: confirm no regressions",
    "",
    "### Artifact saved",
    "`fix.md` written to `.waypoint/fix.md`.",
    "",
    "### Suggested next step",
    "Run `waypoint_test` after applying the fix to confirm no regressions.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
