import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_goal",
  description:
    "Define or refine the project goal. Analyzes existing code and business logic if present.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
      goal: {
        type: "string",
        description:
          "The goal to define or refine. Omit to review an existing goal.md.",
      },
    },
    required: ["workspacePath"],
  },
};

export async function run(args: {
  workspacePath: string;
  goal?: string;
}): Promise<string> {
  const { workspacePath, goal } = args;

  const ctx = await getBaseContext(workspacePath);
  const existing = await getArtifact(workspacePath, "goal.md");

  const goalStatement = goal ?? existing?.match(/^# Goal\n+(.+)/m)?.[1] ?? null;

  const workspaceSummary = [
    `**Path:** ${workspacePath}`,
    ctx.packageJson
      ? `**Package:** ${(() => {
          try {
            const p = JSON.parse(ctx.packageJson!);
            return `${p.name ?? "unnamed"} v${p.version ?? "?"}`;
          } catch {
            return "present (unparseable)";
          }
        })()}`
      : "**Package:** none detected",
    `**Files (2 levels):**\n\`\`\`\n${ctx.fileTree}\n\`\`\``,
    Object.keys(ctx.waypointArtifacts).length > 0
      ? `**Existing .waypoint artifacts:** ${Object.keys(ctx.waypointArtifacts).join(", ")}`
      : "**Existing .waypoint artifacts:** none",
  ].join("\n");

  if (!goalStatement) {
    return [
      "## waypoint_goal — No goal defined yet",
      "",
      "### Workspace snapshot",
      workspaceSummary,
      "",
      "### Next step",
      "Call `waypoint_goal` again with a `goal` parameter describing what you want to achieve.",
      "Example: _\"Add user authentication with email/password and OAuth\"_",
      "",
      "A clear goal should answer:",
      "- What capability or outcome are we delivering?",
      "- Who benefits and how?",
      "- What does done look like?",
    ].join("\n");
  }

  const artifact = [
    "# Goal",
    "",
    goalStatement,
    "",
    "## Success criteria",
    "<!-- Define 2-4 measurable outcomes that confirm this goal is met -->",
    "- [ ] ",
    "",
    "## Out of scope",
    "<!-- Explicitly list what this goal does NOT cover -->",
    "- ",
    "",
    "## Workspace observations",
    workspaceSummary,
    "",
    `_Generated by waypoint_goal — ${new Date().toISOString()}_`,
  ].join("\n");

  await saveArtifact(workspacePath, "goal.md", artifact);

  return [
    "## waypoint_goal — Goal captured",
    "",
    `**Goal:** ${goalStatement}`,
    "",
    "### Workspace snapshot",
    workspaceSummary,
    "",
    "### Artifact saved",
    "`goal.md` written to `.waypoint/goal.md`.",
    "Fill in **Success criteria** and **Out of scope** before moving to `waypoint_research`.",
    "",
    "### Suggested next step",
    "Run `waypoint_research` to surface best practices and open questions for this goal.",
  ].join("\n");
}
