import { getBaseContext, getArtifact, saveArtifact, clearArtifacts } from "../context.js";

export const definition = {
  name: "waypoint_goal",
  description:
    "Start here. Define or refine the project goal — writes goal.md. Run before all other waypoint tools. If a goal already exists, calling with a new goal will ask you to confirm before archiving the current cycle.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root. Defaults to the current working directory.",
      },
      goal: {
        type: "string",
        description:
          "The goal to define or refine. Omit to review an existing goal.md.",
      },
      confirmArchive: {
        type: "boolean",
        description:
          "Set to true to confirm archiving the existing cycle and starting a new one. Required when a goal already exists and you are providing a new goal.",
      },
    },
    required: [],
  },
};

export async function run(args: {
  workspacePath?: string;
  goal?: string;
  confirmArchive?: boolean;
}): Promise<string> {
  const { workspacePath = process.cwd(), goal, confirmArchive } = args;

  const ctx = await getBaseContext(workspacePath);
  const existing = await getArtifact(workspacePath, "goal.md");

  // When a new goal is given and a prior cycle exists, require explicit confirmation before archiving
  if (goal && existing && !confirmArchive) {
    const previousGoal = existing.match(/^# Goal\n+(.+)/m)?.[1] ?? "(unknown)";
    return [
      "## waypoint_goal — Existing cycle detected",
      "",
      `**Current goal:** ${previousGoal}`,
      "",
      "Proceeding will archive the current cycle (all .waypoint artifacts will be moved to previous.md) and start a new one.",
      "",
      "**To confirm:** call `waypoint_goal` again with `confirmArchive: true`.",
      "**To cancel:** call `waypoint_goal` without a `goal` param to review the existing goal instead.",
    ].join("\n");
  }

  // When a new goal is given and a prior cycle exists, snapshot it to previous.md
  if (goal && existing && confirmArchive) {
    const cycleArtifacts = [
      "research.md", "compare.md", "plan.md", "design.md",
      "build.md", "test.md", "audit.md", "measure.md", "review.md",
    ];
    const present = (
      await Promise.all(cycleArtifacts.map(n => getArtifact(workspacePath, n)))
    )
      .map((content, i) => (content ? cycleArtifacts[i] : null))
      .filter(Boolean) as string[];

    const previousGoal = existing.match(/^# Goal\n+(.+)/m)?.[1] ?? "(unknown)";
    const previousMd = [
      "# Previous cycle",
      "",
      `**Goal:** ${previousGoal}`,
      `**Closed:** ${new Date().toISOString()}`,
      `**Artifacts at close:** ${present.length > 0 ? present.join(", ") : "none"}`,
      "",
      "## Previous goal",
      existing,
    ].join("\n");

    await saveArtifact(workspacePath, "previous.md", previousMd);
    // Clear stale cycle artifacts so they don't pollute the new cycle's context
    await clearArtifacts(workspacePath, present);
  }

  const goalStatement = goal ?? existing?.match(/^# Goal\n+(.+)/m)?.[1] ?? null;

  const workspaceSummary = [
    `**Path:** ${workspacePath}`,
    ctx.packageJson
      ? `**Package:** ${(() => {
          try {
            const p = JSON.parse(ctx.packageJson!);
            return `${p.name ?? "unnamed"} v${p.version ?? "?"}`;
          } catch {
            return "present (unparseable)";
          }
        })()}`
      : "**Package:** none detected",
    `**Files (2 levels):**\n\`\`\`\n${ctx.fileTree}\n\`\`\``,
    Object.keys(ctx.waypointArtifacts).length > 0
      ? `**Existing .waypoint artifacts:** ${Object.keys(ctx.waypointArtifacts).join(", ")}`
      : "**Existing .waypoint artifacts:** none",
  ].join("\n");

  if (!goalStatement) {
    return [
      "## waypoint_goal — No goal defined yet",
      "",
      "### Workspace snapshot",
      workspaceSummary,
      "",
      "### Next step",
      "Call `waypoint_goal` again with a `goal` parameter describing what you want to achieve.",
      "Example: _\"Add user authentication with email/password and OAuth\"_",
      "",
      "A clear goal should answer:",
      "- What capability or outcome are we delivering?",
      "- Who benefits and how?",
      "- What does done look like?",
    ].join("\n");
  }

  const artifact = [
    "# Goal",
    "",
    goalStatement,
    "",
    "## Success criteria",
    "<!-- Define 2-4 measurable outcomes that confirm this goal is met -->",
    "- [ ] ",
    "",
    "## Out of scope",
    "<!-- Explicitly list what this goal does NOT cover -->",
    "- ",
    "",
    "## Workspace observations",
    workspaceSummary,
    "",
    `_Generated by waypoint_goal — ${new Date().toISOString()}_`,
  ].join("\n");

  await saveArtifact(workspacePath, "goal.md", artifact);

  return [
    "## waypoint_goal — Goal captured",
    "",
    `**Goal:** ${goalStatement}`,
    "",
    "### Workspace snapshot",
    workspaceSummary,
    "",
    "### Artifact saved",
    "`goal.md` written to `.waypoint/goal.md`.",
    existing ? "Previous cycle archived to `previous.md` and stale artifacts cleared." : "",
    "",
    "> **Now:** Open `.waypoint/goal.md` and fill in **Success criteria** and **Out of scope** before calling any other waypoint tool.",
  ].join("\n");
}
