import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_improve",
  description:
    "Propose refinements. Distinguish must-haves from optional enhancements.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
      area: {
        type: "string",
        description:
          "Specific area to improve (optional). Omit to generate improvements across all areas.",
      },
    },
    required: ["workspacePath"],
  },
};

export async function run(args: {
  workspacePath: string;
  area?: string;
}): Promise<string> {
  const { workspacePath, area } = args;

  const ctx = await getBaseContext(workspacePath);
  const goalArtifact = await getArtifact(workspacePath, "goal.md");
  const measureArtifact = await getArtifact(workspacePath, "measure.md");
  const buildArtifact = await getArtifact(workspacePath, "build.md");

  if (!goalArtifact) {
    return [
      "## waypoint_improve — No goal found",
      "",
      "Run `waypoint_goal` first — improvements require a defined goal to improve toward.",
    ].join("\n");
  }

  const goalLine = goalArtifact.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";
  const hasMeasure = !!measureArtifact;

  const artifact = [
    "# Improve",
    "",
    `**Goal:** ${goalLine}`,
    area ? `**Area:** ${area}` : "",
    !hasMeasure
      ? "\n> ⚠️ No measure.md found — running `waypoint_measure` first gives better improvement signals."
      : "",
    "",
    "## Must-have improvements",
    "<!-- Fixes that affect correctness, reliability, or core usability — do these now -->",
    "- [ ] ",
    "",
    "## Should-have improvements",
    "<!-- Meaningful quality improvements — do before next major release -->",
    "- [ ] ",
    "",
    "## Nice-to-have enhancements",
    "<!-- Optional upgrades — only if time and priority allow -->",
    "- [ ] ",
    "",
    "## Out of scope",
    "<!-- Improvements explicitly not being pursued and why -->",
    "- ",
    "",
    "## Improvement prompts for AI coding tools",
    "",
    "### Refactor prompt",
    "```",
    `Improve the following area without changing behavior: ${area ?? goalLine}`,
    "",
    "Constraints:",
    "- Do not change externally observable behavior",
    "- Keep changes focused on the area being improved",
    "- Prefer simplicity over cleverness",
    "```",
    "",
    `_Generated by waypoint_improve — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "improve.md", artifact);

  return [
    "## waypoint_improve — Improvement plan generated",
    "",
    `**Goal:** ${goalLine}`,
    area ? `**Area:** ${area}` : "",
    !hasMeasure
      ? "\n> No measure.md found — run `waypoint_measure` for data-driven improvements."
      : "",
    "",
    "### Three tiers",
    "- **Must-have** — correctness and reliability issues; do these now",
    "- **Should-have** — meaningful quality improvements; do before next release",
    "- **Nice-to-have** — optional enhancements; defer unless time allows",
    "",
    "### Artifact saved",
    "`improve.md` written to `.waypoint/improve.md`.",
    "",
    "### Suggested next step",
    "Run `waypoint_document` to document the improved state, or `waypoint_review` for a final quality check.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
