import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_measure",
  description: "Evaluate overall project success against defined goals.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
    },
    required: ["workspacePath"],
  },
};

export async function run(args: {
  workspacePath: string;
}): Promise<string> {
  const { workspacePath } = args;

  const ctx = await getBaseContext(workspacePath);
  const goalArtifact = await getArtifact(workspacePath, "goal.md");
  const buildArtifact = await getArtifact(workspacePath, "build.md");
  const testArtifact = await getArtifact(workspacePath, "test.md");

  if (!goalArtifact) {
    return [
      "## waypoint_measure — No goal found",
      "",
      "Run `waypoint_goal` first — measurement requires a defined goal to evaluate against.",
    ].join("\n");
  }

  const goalLine = goalArtifact.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";

  const successCriteriaBlock = goalArtifact.match(
    /## Success criteria\n([\s\S]*?)(?=\n##|$)/
  )?.[1]?.trim() ?? "";

  const criteriaLines = successCriteriaBlock
    .split("\n")
    .filter((l) => l.trim().startsWith("- ["))
    .map((l) => l.trim());

  const criteriaRows = criteriaLines.length > 0
    ? criteriaLines.map((c) => `| ${c} | | |`)
    : ["| - (no criteria defined in goal.md) | | |"];

  const missing = [
    !buildArtifact && "build.md",
    !testArtifact && "test.md",
  ].filter(Boolean);

  const artifact = [
    "# Measure",
    "",
    `**Goal:** ${goalLine}`,
    missing.length > 0
      ? `\n> ⚠️ Missing: ${missing.join(", ")} — measurement may be incomplete.`
      : "",
    "",
    "## Success criteria scorecard",
    "| Criterion | Status | Evidence |",
    "|-----------|--------|----------|",
    ...criteriaRows,
    "",
    "## Overall verdict",
    "<!-- One of: ✅ Goal met | ⚠️ Partially met | ❌ Not met -->",
    "**Verdict:** ",
    "**Summary:** ",
    "",
    "## What worked well",
    "- ",
    "",
    "## What fell short",
    "- ",
    "",
    "## Quantitative signals",
    "<!-- Add any measurable data: test pass rate, latency, bundle size, etc. -->",
    "| Metric | Target | Actual | Pass? |",
    "|--------|--------|--------|-------|",
    "| | | | |",
    "",
    `_Generated by waypoint_measure — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "measure.md", artifact);

  return [
    "## waypoint_measure — Measurement framework generated",
    "",
    `**Goal:** ${goalLine}`,
    missing.length > 0 ? `\n> Missing: ${missing.join(", ")} — add these for fuller measurement.` : "",
    "",
    criteriaLines.length > 0
      ? `**${criteriaLines.length} success criteria** pulled from goal.md into scorecard.`
      : "**No success criteria found in goal.md.** Fill in the scorecard manually.",
    "",
    "### How to use measure.md",
    "1. Score each criterion: ✅ met / ⚠️ partial / ❌ not met",
    "2. Add evidence for each",
    "3. Record quantitative signals where available",
    "4. Write the overall verdict",
    "",
    "### Artifact saved",
    "`measure.md` written to `.waypoint/measure.md`.",
    "",
    "### Suggested next step",
    "Run `waypoint_improve` to identify refinements based on what fell short.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
