import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_plan",
  description:
    "Create a structured plan for new features or significant changes only.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
      scope: {
        type: "string",
        description:
          "Specific scope or milestone to plan (optional). Omit to plan the full goal.",
      },
    },
    required: ["workspacePath"],
  },
};

export async function run(args: {
  workspacePath: string;
  scope?: string;
}): Promise<string> {
  const { workspacePath, scope } = args;

  const ctx = await getBaseContext(workspacePath);
  const goalArtifact = await getArtifact(workspacePath, "goal.md");
  const optionsArtifact = await getArtifact(workspacePath, "compare.md");
  const researchArtifact = await getArtifact(workspacePath, "research.md");

  if (!goalArtifact) {
    return [
      "## waypoint_plan — No goal found",
      "",
      "Run `waypoint_goal` before planning.",
    ].join("\n");
  }

  const goalLine = goalArtifact.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";
  const missing = [
    !researchArtifact && "research.md",
    !optionsArtifact && "compare.md",
  ].filter(Boolean);

  const artifact = [
    "# Plan",
    "",
    `**Goal:** ${goalLine}`,
    scope ? `**Scope:** ${scope}` : "",
    missing.length > 0
      ? `\n> ⚠️ Missing prior artifacts: ${missing.join(", ")}. Plan may be incomplete.`
      : "",
    "",
    "## Milestones",
    "<!-- Break the work into 2–5 ordered milestones -->",
    "",
    "### Milestone 1 — Foundation",
    "**Deliverable:** ",
    "**Done when:** ",
    "**Steps:**",
    "- [ ] ",
    "",
    "### Milestone 2 — Core feature",
    "**Deliverable:** ",
    "**Done when:** ",
    "**Steps:**",
    "- [ ] ",
    "",
    "### Milestone 3 — Polish & ship",
    "**Deliverable:** ",
    "**Done when:** ",
    "**Steps:**",
    "- [ ] ",
    "",
    "## Dependencies",
    "<!-- External dependencies or blockers between milestones -->",
    "- ",
    "",
    "## Out of scope for this plan",
    "- ",
    "",
    "## Risk register",
    "| Risk | Likelihood | Impact | Mitigation |",
    "|------|-----------|--------|------------|",
    "| | | | |",
    "",
    `_Generated by waypoint_plan — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "plan.md", artifact);

  return [
    "## waypoint_plan — Plan generated",
    "",
    `**Goal:** ${goalLine}`,
    scope ? `**Scope:** ${scope}` : "",
    missing.length > 0
      ? `\n> Missing: ${missing.join(", ")} — plan may be incomplete.`
      : "",
    "",
    "### Structure",
    "- **3 milestones** scaffolded — fill in deliverables, done-when criteria, and steps",
    "- **Risk register** — add any known risks before building",
    "- **Dependencies** — note anything that must be resolved first",
    "",
    "### Artifact saved",
    "`plan.md` written to `.waypoint/plan.md`.",
    "",
    "### Suggested next step",
    "Run `waypoint_build` to scaffold implementation from this plan.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
