import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_research",
  description:
    "Gather best practices, surface the right questions, explore the solution space.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
      topic: {
        type: "string",
        description:
          "Specific research focus (optional). Omit to research the full goal.",
      },
    },
    required: ["workspacePath"],
  },
};

export async function run(args: {
  workspacePath: string;
  topic?: string;
}): Promise<string> {
  const { workspacePath, topic } = args;

  const ctx = await getBaseContext(workspacePath);
  const goalArtifact = await getArtifact(workspacePath, "goal.md");

  if (!goalArtifact) {
    return [
      "## waypoint_research — No goal found",
      "",
      "Run `waypoint_goal` first to define the project goal before researching.",
    ].join("\n");
  }

  const goalLine = goalArtifact.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";
  const focus = topic ?? goalLine;

  const artifact = [
    "# Research",
    "",
    `**Goal:** ${goalLine}`,
    topic ? `**Focus:** ${topic}` : "",
    "",
    "## Key questions to answer",
    "<!-- What must be understood before committing to a design? -->",
    "- What existing solutions or libraries handle this well?",
    "- What constraints (performance, security, compatibility) apply?",
    "- What has failed in similar past attempts?",
    "- What unknowns could invalidate the plan?",
    "",
    "## Areas to investigate",
    "",
    "### Prior art & libraries",
    "- [ ] Survey existing libraries and tools relevant to the goal",
    "- [ ] Review documentation and known limitations",
    "",
    "### Architecture & patterns",
    "- [ ] Identify applicable design patterns",
    "- [ ] Assess integration points with existing code",
    "",
    "### Risks & constraints",
    "- [ ] List technical risks",
    "- [ ] Note hard constraints (runtime, platform, team)",
    "",
    "### Open decisions",
    "<!-- Questions that will need to be resolved in waypoint_compare -->",
    "- [ ] ",
    "",
    "## Workspace observations",
    `**Path:** ${workspacePath}`,
    ctx.packageJson
      ? (() => {
          try {
            const p = JSON.parse(ctx.packageJson!);
            return `**Package:** ${p.name ?? "unnamed"} v${p.version ?? "?"}`;
          } catch {
            return "**Package:** present (unparseable)";
          }
        })()
      : "**Package:** none detected",
    "",
    `_Generated by waypoint_research — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "research.md", artifact);

  return [
    "## waypoint_research — Research brief generated",
    "",
    `**Goal:** ${goalLine}`,
    topic ? `**Focus:** ${topic}` : "",
    "",
    "### What to investigate",
    "1. **Prior art & libraries** — survey what exists, note limitations",
    "2. **Architecture & patterns** — find applicable patterns, assess fit",
    "3. **Risks & constraints** — surface blockers early",
    "4. **Open decisions** — list what must be resolved before planning",
    "",
    "### Artifact saved",
    "`research.md` written to `.waypoint/research.md`.",
    "Fill in findings before moving forward.",
    "",
    "### Suggested next step",
    "Run `waypoint_compare` to turn research findings into concrete decision tradeoffs.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
