import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_review",
  description:
    "Final quality check before shipping or handoff. Reads all prior artifacts.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root.",
      },
    },
    required: ["workspacePath"],
  },
};

const ALL_ARTIFACTS = [
  "goal.md",
  "research.md",
  "compare.md",
  "plan.md",
  "design.md",
  "build.md",
  "test.md",
  "fix.md",
  "debug.md",
  "audit.md",
  "measure.md",
  "improve.md",
  "docs.md",
] as const;

export async function run(args: {
  workspacePath: string;
}): Promise<string> {
  const { workspacePath } = args;

  const ctx = await getBaseContext(workspacePath);
  const goalArtifact = await getArtifact(workspacePath, "goal.md");

  if (!goalArtifact) {
    return [
      "## waypoint_review — No goal found",
      "",
      "Run `waypoint_goal` first — review requires a defined goal to evaluate against.",
    ].join("\n");
  }

  const goalLine = goalArtifact.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";

  // inventory all artifacts
  const inventory: { name: string; present: boolean }[] = [];
  for (const name of ALL_ARTIFACTS) {
    const content = await getArtifact(workspacePath, name);
    inventory.push({ name, present: !!content });
  }

  const present = inventory.filter((a) => a.present);
  const missing = inventory.filter((a) => !a.present);

  const inventoryRows = inventory.map(
    (a) => `| ${a.name} | ${a.present ? "✅" : "❌"} |`
  );

  const artifact = [
    "# Review",
    "",
    `**Goal:** ${goalLine}`,
    "",
    "## Artifact inventory",
    "| Artifact | Present |",
    "|----------|---------|",
    ...inventoryRows,
    "",
    `**${present.length} of ${ALL_ARTIFACTS.length} artifacts present.**`,
    missing.length > 0
      ? `Missing: ${missing.map((a) => a.name).join(", ")}`
      : "All artifacts present.",
    "",
    "## Pre-ship checklist",
    "<!-- Work through these before marking done -->",
    "",
    "### Goal",
    "- [ ] Goal is clearly stated and success criteria are defined",
    "- [ ] All success criteria are met (see measure.md)",
    "",
    "### Code quality",
    "- [ ] No dead code or commented-out blocks",
    "- [ ] No hardcoded values that should be configuration",
    "- [ ] Error states produce safe, clear output",
    "",
    "### Tests",
    "- [ ] Happy path tested",
    "- [ ] Edge cases tested",
    "- [ ] No known failing tests",
    "",
    "### Documentation",
    "- [ ] README or docs.md reflects current state",
    "- [ ] Breaking changes documented",
    "",
    "### Security",
    "- [ ] No secrets or credentials in code or artifacts",
    "- [ ] Input validation at system boundaries",
    "",
    "## Reviewer notes",
    "<!-- Open issues, questions for the team, or follow-up items -->",
    "- ",
    "",
    "## Verdict",
    "<!-- ✅ Ready to ship | ⚠️ Ship with caveats | ❌ Not ready -->",
    "**Verdict:** ",
    "**Rationale:** ",
    "",
    `_Generated by waypoint_review — ${new Date().toISOString()}_`,
  ].join("\n");

  await saveArtifact(workspacePath, "review.md", artifact);

  return [
    "## waypoint_review — Final review generated",
    "",
    `**Goal:** ${goalLine}`,
    "",
    `### Artifact inventory: ${present.length}/${ALL_ARTIFACTS.length} present`,
    ...inventory.map((a) => `- ${a.present ? "✅" : "❌"} ${a.name}`),
    "",
    "### Pre-ship checklist covers",
    "Goal, code quality, tests, documentation, security",
    "",
    "### Artifact saved",
    "`review.md` written to `.waypoint/review.md`.",
    "Complete the checklist and record your verdict.",
    "",
    missing.length > 0
      ? `### Missing artifacts\nConsider running: ${missing.map((a) => `\`waypoint_${a.name.replace(".md", "")}\``).join(", ")}`
      : "### All artifacts present — ready for final checklist.",
  ].join("\n");
}
