import { getBaseContext, getArtifact, saveArtifact } from "../context.js";

export const definition = {
  name: "waypoint_test",
  description:
    "Generate test checklists and prompts for feature requirements — writes test.md. Does not run tests or edit source files. Run after waypoint_build.",
  inputSchema: {
    type: "object" as const,
    properties: {
      workspacePath: {
        type: "string",
        description: "Absolute path to the workspace root. Defaults to the current working directory.",
      },
      feature: {
        type: "string",
        description:
          "Specific feature or behavior to test (optional). Omit to test all built features.",
      },
    },
    required: [],
  },
};

export async function run(args: {
  workspacePath?: string;
  feature?: string;
}): Promise<string> {
  const { workspacePath = process.cwd(), feature } = args;

  const ctx = await getBaseContext(workspacePath);
  const buildArtifact = await getArtifact(workspacePath, "build.md");
  const goalArtifact = await getArtifact(workspacePath, "goal.md");

  if (!buildArtifact && !goalArtifact) {
    return [
      "## waypoint_test — No build or goal found",
      "",
      "Run `waypoint_build` before testing.",
    ].join("\n");
  }

  const goalLine = goalArtifact?.match(/^# Goal\n+(.+)/m)?.[1] ?? "(goal not parsed)";
  const hasBuild = !!buildArtifact;
  const focus = feature ?? goalLine;

  const artifact = [
    "# Test",
    "",
    `**Goal:** ${goalLine}`,
    feature ? `**Feature under test:** ${feature}` : "",
    !hasBuild ? "\n> ⚠️ No build.md found — test coverage may be incomplete." : "",
    "",
    "## Feature checklist",
    "<!-- Verify each feature works as intended from a user perspective -->",
    `- [ ] ${focus} — happy path works end to end`,
    "- [ ] Edge cases handled correctly",
    "- [ ] Error states produce clear, safe output",
    "- [ ] No regressions in adjacent functionality",
    "",
    "## Test prompts for AI coding tools",
    "",
    "### Unit test prompt",
    "```",
    `Write unit tests for: ${focus}`,
    "Requirements:",
    "- Test the happy path",
    "- Test at least 2 edge cases",
    "- Test error/failure paths",
    "- No mocks unless absolutely necessary",
    "```",
    "",
    "### Integration test prompt",
    "```",
    `Write integration tests for: ${focus}`,
    "Requirements:",
    "- Exercise the full stack from entry point to output",
    "- Verify against real data or fixtures, not mocks",
    "- Assert on observable behavior, not implementation details",
    "```",
    "",
    "## Manual test cases",
    "<!-- Scenarios that are hard to automate -->",
    "| Scenario | Steps | Expected | Actual | Pass? |",
    "|----------|-------|----------|--------|-------|",
    "| Happy path | | | | |",
    "| Empty input | | | | |",
    "| Invalid input | | | | |",
    "",
    "## Known gaps",
    "<!-- Tests not written yet and why -->",
    "- ",
    "",
    `_Generated by waypoint_test — ${new Date().toISOString()}_`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  await saveArtifact(workspacePath, "test.md", artifact);

  return [
    "## waypoint_test — Test plan generated",
    "",
    `**Goal:** ${goalLine}`,
    feature ? `**Feature:** ${feature}` : "",
    !hasBuild ? "\n> No build.md found — test plan may be incomplete." : "",
    "",
    "### Coverage areas",
    "- **Feature checklist** — happy path, edge cases, errors, regressions",
    "- **AI test prompts** — unit and integration test generation",
    "- **Manual test cases** — scenarios needing human verification",
    "",
    "### Artifact saved",
    "`test.md` written to `.waypoint/test.md`.",
    "",
    "### Suggested next step",
    "If tests reveal bugs, run `waypoint_fix`. Otherwise run `waypoint_measure` to evaluate overall success.",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
